prereq:
  packages:
    yum:
      # ajenti
      - gcc
      - python-devel
      - python-pip
      - libxslt-devel
      - libxml2-devel
      - libffi-devel
      - openssl-devel
      - libjpeg-turbo-devel
      - libpng-devel
      - dbus-python
      # ajenti dev
      - python-augeas
      - ntpdate
      - nodejs
      - git
      - openldap-devel
      # webmin
      - perl
      - perl-Net-SSLeay
      - openssl
      - perl-IO-Tty
      - perl-Encode-Detect
      # cockpit dev
      - yum-utils
      - curl
      - expect
      - libvirt
      - libvirt-client
      - libvirt-daemon
      - libvirt-python
      - python
      - python-libguestfs
      - python-lxml
      - libguestfs-xfs
      - python3
      - libvirt-python3
      - libguestfs-tools
      - qemu
      - qemu-kvm
      - rpm-build
      - rsync
      - xz
    pip:
      - wheel
      - setuptools
      - distribute
      # AWX
      - ansible
    npm:
      # ajenti dev
      - bower
      - babel-cli
      - babel-preset-es2015
      - babel-plugin-external-helpers
      - less
      - coffee-script
      - angular-gettext-cli
      - angular-gettext-tools
      # Cockpit dev
      - webpack
